[package]
authors = ["Jet Li <jing.i.qin@icloud.com>"]
categories = ["wasm"]
description = "Exemplary real world app built with Rust + Yew + WebAssembly."
edition = "2021"
license = "Apache-2.0/MIT"
name = "frontend"
repository = "https://github.com/jetli/rust-yew-realworld-example-app.git"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
gloo = "0.8"
lazy_static = "1.4.0"
log = "0.4"
parking_lot = "0.12.1"
pulldown-cmark = "0.9.2"
reqwest = { version = "0.11.13", features = ["json"] }
serde = "1"
thiserror = "1"
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17.0"
yew-hooks = "0.2.0"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
reqwasm = "0.5.0"
web3 = { git = "https://github.com/monomadic/rust-web3", default-features = false, features = ["http-rustls-tls", "wasm", "eip-1193"] }
yew-ethereum-provider = { git = "https://github.com/monomadic/yew-ethereum-provider" }

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "Node",
  "Window",
  "HtmlCollection",
  "HtmlInputElement",
]

[dev-dependencies]
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"
gloo-utils = "0.1.5"